### PR TITLE
fixed significant vision improvements

### PR DESCRIPTION
**Pull request by yourordinarycat**
i missed having myopia so i replaced this mica medicine thing with [REDACTED]

before pic
image

after pics
image
image
image

### CODE REVIEW

**Comment by josephbeattie** [comment]
😂 very funny. Acrylic reigns supreme! @YourOrdinaryCat are you trying to start a war?

**Comment by itsWindows11** [comment]
bruh moment

**Comment by dongle-the-gadget** [comment]
I can tell that this PR will get closed and probably the guys around here would get perma ban from this repo as well.

**Comment by FireCubeStudios** [comment]
This is a war crime against humanity that violates several human rights and international treaties. You will be sent to an independant tribunal to face trials for your crimes

**Pull request closed without merging**
